FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install

# Not needed for dev since we are mapping to local volume
# But this is needed for production build
# COPY . .

CMD ["npm", "run", "start"]
